// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3W3nc9XEu8z2CIGTGdgC67YCkJr48HNU',
    appId: '1:463660836835:web:99f0034c6d7a819ea6e2d6',
    messagingSenderId: '463660836835',
    projectId: 'myproject-58d81',
    authDomain: 'myproject-58d81.firebaseapp.com',
    storageBucket: 'myproject-58d81.firebasestorage.app',
    measurementId: 'G-SWXM1KZ4J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsHLO0p-3nTQ6GDQ6P4K3WX0cgAhR5CvM',
    appId: '1:463660836835:android:7c9e88de91af871fa6e2d6',
    messagingSenderId: '463660836835',
    projectId: 'myproject-58d81',
    storageBucket: 'myproject-58d81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVuFfnp2lj9jglMJp8RRIM7DU-IkAzE58',
    appId: '1:463660836835:ios:675c3654128a8ecea6e2d6',
    messagingSenderId: '463660836835',
    projectId: 'myproject-58d81',
    storageBucket: 'myproject-58d81.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVuFfnp2lj9jglMJp8RRIM7DU-IkAzE58',
    appId: '1:463660836835:ios:675c3654128a8ecea6e2d6',
    messagingSenderId: '463660836835',
    projectId: 'myproject-58d81',
    storageBucket: 'myproject-58d81.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3W3nc9XEu8z2CIGTGdgC67YCkJr48HNU',
    appId: '1:463660836835:web:bff358ca55dee5a0a6e2d6',
    messagingSenderId: '463660836835',
    projectId: 'myproject-58d81',
    authDomain: 'myproject-58d81.firebaseapp.com',
    storageBucket: 'myproject-58d81.firebasestorage.app',
    measurementId: 'G-W3G52E8MNC',
  );

}